---
title: "Ideas about monopolies"
author: "A. J. Rominger"
date: "`r format(Sys.time(), '%d %B %Y')`"
tags: equality policy economics
output: 
  md_document:
    variant: markdown_github
bibliography: notes.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

An interesting [article](https://www.theatlantic.com/business/archive/2017/06/word-monopoly-antitrust/530169/?utm_source=feed) in the *Atlantic* today documents the rise and fall of public interest in monopolies and, by extension, a fall in opposition to their detrimental effects on society.  The article links to sources documenting some of those detrimental effects, including income inequality and stagnant wages.

This made me recall another interesting [article](https://www.theatlantic.com/politics/archive/2016/10/how-democrats-killed-their-populist-soul/504710/) (also in the *Atlantic*) about how the Democratic Party was taken over by cooperate-leaning groups and "lost its populist soul," including adopting the view that monopolies were actually good for society because of economies of scale they could provide.

In all we see that when an issue falls out of public interest or favor, we see the co-option of the political process by financial interests that may not be in the people's interest.  This implies a constant struggle between the awareness and advocacy---to influence politicians and affect change---of citizens for their best interest, and the financially-driven interest of the few.  Those with financial power will use it to affect change for their own benefit.  In the current system this cannot be prevented without active public interest and involvement (based on sound information) in politics.  Antitrust legislation should have protected the public from "corporate dictatorship" (quote from [FRD speach](http://www.presidency.ucsb.edu/ws/?pid=15314)) but it didn't.  This could either be because the public forgot to care about monopolies and thus monopolistic groups could hold sway over government decisions (as the first [article](https://www.theatlantic.com/business/archive/2017/06/word-monopoly-antitrust/530169/?utm_source=feed) suggests) or it could be that monopolistic groups forced the government to force the people to forget to care.  We need to figure out which one, and figure out how to prevent that from continuing to happen.  Is apathy a property of the people or a property of a corrupt system?
