---
title: "Notes on the SFI postdoc conference today"
author: "A. J. Rominger"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
bibliography: notes.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lunch with Artemy
What can we learn from parameterizing an Ising model for spatial occupancy?

- calculate box counting function across scales
- compare spatial box counting to Poisson process
- We know from Harte's work that spatial patterns aren't fractal, but there's a chance they could still be critical in the Ising model due to the finite lattice of sampled communities
- But perhaps more likely, systems are sub-critical
- What could we learn from the distribution of Ising model parameters across co-occurring species?

# Ideas from talks
- Look into [Elizabeth Roberto's work](http://www.elizabethroberto.com/research) on spatial inequality in cities
- Are Lauren Shoemaker's models of coexistence facilitated by environmental stochasticity similar to Chesson's storage effect model?
- Detailed models of coexistence concern themselves with the persistence of identifiable species; this contrasts with most (all?) null/neutral/statistical models of SADs which concern themselves with macroscopic patterns of (usually) indistinguishable species.  Equilibria in these null models are for the macrostate but ambivilant about the microstates (sensu MacArthur and Wilson's "dynamic equilibrium"), while equilibria in coexistence models are defined on the microstates.  From the macroscopic perspective, does the term "stabely coexist" really matter?
- Marion could be a good person to ask and work with about social networks and fake news...she might have already done it
- Social cognition could be the right framing for thinking about how bias against groups in perpetuated
- Dan, Marion and Elly have a cool sounding project on reputational poverty traps. This seemed more like it was for networks where reputation is biased by associate, but they might be interested in thinking about the "poverty traps" imposed by implicit biases...that may or may not have a basis in networks
